---
# tasks file for influxdb
- name: Import InfluxDB GPG signing key
  apt_key: 
    url: https://repos.influxdata.com/influxdb.key 
    state: present

- name: Add InfluxDB repository
  apt_repository: 
    repo: ' deb https://repos.influxdata.com/ubuntu trusty stable' 
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: Instal InfluxDB package
  apt: 
    name: influxdb 
    state: present

- name: Modify Influx hostname
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes
    
- name: Start Influx Service
  service: 
    name: influxdb 
    state: restarted
          
