---
# tasks file for lamp_centos
- name: Install httpd
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: Add httpd HTML File
  copy:
    content: "Welcome to Apache"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: httpd

- name: Start httpd
  service:
    name: httpd
    state: started
  when: httpd.changed

- name: Stop firewall
  service:
    name: firewalld
    state: stopped

- name: Install MariaDB
  yum:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: Add file for mysql
  copy:
    content: "Welcome to MySQL"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql

- name: start mariadb
  service:
    name: mariadb
    state: started
  when: mysql.changed

- name: Install php
  yum:
    name:
      - php
      - php-mysqlnd
    state: latest
    update_cache: yes

- name: Add html file for php
  copy:
    content: "Welcome to PHP"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
  register: php

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  when: php.changed
# tasks file for roles/centos/Lamp
