---
# tasks file for influxdb_centos
- name: import gpg key
  rpm_key:
    key: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add influxdb repo
  yum_repository:
    name: influxdb
    description: Adds influxdb repository
    baseurl: https://repos.influxdata.com/rhel/7/x86_64/stable/
    enabled: true
    gpgcheck: true
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: update cache
  dnf:
    update_cache: yes

- name: install influxdb package
  yum:
    name: influxdb
    state: present

- name: Modify influx hostname
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes

- name: Start influx service
  service:
    name: influxdb
    state: restarted
    
