---
# tasks file for lamp-ubuntu
- name: Install apache2
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Add html file for apache
  copy:
    content: "Welcome to Apache"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index

- name: Restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: apache_index.changed

- name: Whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Install mysql
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Add html file for mysql
  copy:
    content: "Welcome to MySQL"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: Start mysql 
  service:
    name: mysql
    state: started
    enabled: yes
  when: mysql_index.changed

- name: Install php
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: Add html file for php
  copy:
    content: "Welcome to PHP"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
